day_of_christmas = int(input("Enter number from 1 to 12 to print the day: "))
match day_of_christmas:
  case 1: print("On the first day of Christmas My true love sent to me")
  case 2: print("On the second day of Christmas My true love sent to me")
  case 3: print("On the third day of Christmas My true love sent to me")
  case 4: print("On the fourth day of Christmas My true love sent to me")
  case 5: print("On the fifth day of Christmas My true love sent to me")
  case 6: print("On the sixth day of Christmas My true love sent to me")
  case 7: print("On the seventh day of Christmas My true love sent to me")
  case 8: print("On the eighth day of Christmas My true love sent to me")
  case 9: print("On the ninth day of Christmas My true love sent to me")
  case 10: print("On the tenth day of Christmas My true love sent to me")
  case 11: print("On the eleventh day of Christmas My true love sent to me")
  case 12: print("On the twelfth day of Christmas My true love sent to me") 

gift_of_christmas = int(input("Enter number from 1 to 12 to print the day: "))

match gift_of_christmas:
  case 1: print("A partridge in a pear tree")
  case 2: print("Two turtle doves, and a partridge in a pear tree.")
  case 3: print("Three French hens, two turtle doves, and a partridge in a pear tree.")
  case 4: print("Four calling birds, three french hens, two turtle doves, and a partridge in a pear tree!")
  case 5: print("Five golden rings, four calling birds, three french hens, two turtle doves, and a partridge in a pear tree!")		
  case 6: print("Six geese a laying, five golden rings, four calling birds, three french hens, two turtle doves, and a partridge in a pear tree!")
  case 7: print("Seven swans a swimming, six geese a laying, five golden rings, four calling birds, three french hens, two turtle doves, and a partridge in a pear tree!")
  case 8: print("Eight maids a milking, seven swans a swimming, six geese a laying, five golden rings, four calling birds, three french hens, two turtle doves, and a partridge in a pear tree!")
  case 9: print("Nine ladies dancing, eight maids a milking, seven swans a swimming, six geese a laying, five golden rings, four calling birds, three french hens, two turtle doves, and a partridge in a pear tree!")
  case 10: print("Ten lords a leaping, nine ladies dancing, eight maids a milking, seven swans a swimming, six geese a laying, five golden rings, four calling birds, three french hens, two turtle doves, and a partridge in a pear tree!")
  case 11: print("Eleven pipers piping, ten lords a leaping, nine ladies dancing, eight maids a milking, seven swans a swimming, six geese a laying, five golden rings, four calling birds, three french hens, two turtle doves, and a partridge in a pear tree!")
  case 12: print("Twelve drummers drumming, eleven pipers piping, ten lords a leaping, nine ladies dancing, eight maids a milking, seven swans a swimming, six geese a laying, five golden rings, four calling birds, three french hens, two turtle doves, and a partridge in a pear tree!")